### ISSUE TITLE
Bantu setting bro

### ISSUE THREAD

**Issue by ijalsudekat** [akbaryahya/MultiMining#4]
error kya gini gara2 salah set config ya bro?

Problem: Invalid URI: The format of the URI could not be determined.
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Siakbary.checker.bms.SetProxy()
   at Siakbary.checker.bms.Http(String path, String data)
   at Siakbary.checker.bms.GetTiket(Boolean p)
   at MultiMining.checker.GUI_mybookshow.<StartBot>b__7_0(Object state)

tutor config checker bms nya dong ;)

**Comment by akbaryahya** [comment]
url proxynya harus http://127.0.0.1:80 bukan 127.0.0.1:80
